@startmindmap
* Approach
** Learning
*** Beginner(Developer)
**** 
**** Risk Management Software
**** Risk Analysis Books
**** Risk Management Workshops
*** Asset Valuation
**** Asset Valuation Courses
**** Valuation Models
*** Asset Valuation1
**** Asset Valuation Courses1
**** Valuation Models1

**** Asset Valuation Reports
**** Valuation Conferences
@endmindmap
